// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// initialize_from_matrix
Rcpp::List initialize_from_matrix(Rcpp::NumericMatrix data, int n_neighbors, std::string nn_method, int ndim);
RcppExport SEXP _yaumap_initialize_from_matrix(SEXP dataSEXP, SEXP n_neighborsSEXP, SEXP nn_methodSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< std::string >::type nn_method(nn_methodSEXP);
    Rcpp::traits::input_parameter< int >::type ndim(ndimSEXP);
    rcpp_result_gen = Rcpp::wrap(initialize_from_matrix(data, n_neighbors, nn_method, ndim));
    return rcpp_result_gen;
END_RCPP
}
// initialize_from_neighbors
Rcpp::List initialize_from_neighbors(Rcpp::IntegerMatrix indices, Rcpp::NumericMatrix distances, int ndim);
RcppExport SEXP _yaumap_initialize_from_neighbors(SEXP indicesSEXP, SEXP distancesSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< int >::type ndim(ndimSEXP);
    rcpp_result_gen = Rcpp::wrap(initialize_from_neighbors(indices, distances, ndim));
    return rcpp_result_gen;
END_RCPP
}
// run
Rcpp::NumericMatrix run(SEXP status, int ndim, Rcpp::NumericMatrix embedding);
RcppExport SEXP _yaumap_run(SEXP statusSEXP, SEXP ndimSEXP, SEXP embeddingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type status(statusSEXP);
    Rcpp::traits::input_parameter< int >::type ndim(ndimSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type embedding(embeddingSEXP);
    rcpp_result_gen = Rcpp::wrap(run(status, ndim, embedding));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_yaumap_initialize_from_matrix", (DL_FUNC) &_yaumap_initialize_from_matrix, 4},
    {"_yaumap_initialize_from_neighbors", (DL_FUNC) &_yaumap_initialize_from_neighbors, 3},
    {"_yaumap_run", (DL_FUNC) &_yaumap_run, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_yaumap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
