# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

define_defaults <- function() {
    .Call(`_yaumap_define_defaults`)
}

setup_parameters <- function(local_connectivity, bandwidth, mix_ratio, spread, min_dist, a, b, repulsion_strength, num_epochs, learning_rate, negative_sample_rate, num_neighbors, seed, num_threads) {
    .Call(`_yaumap_setup_parameters`, local_connectivity, bandwidth, mix_ratio, spread, min_dist, a, b, repulsion_strength, num_epochs, learning_rate, negative_sample_rate, num_neighbors, seed, num_threads)
}

initialize_from_matrix <- function(params, data, nn_method, ndim) {
    .Call(`_yaumap_initialize_from_matrix`, params, data, nn_method, ndim)
}

initialize_from_neighbors <- function(params, indices, distances, ndim) {
    .Call(`_yaumap_initialize_from_neighbors`, params, indices, distances, ndim)
}

run <- function(status, nthreads, tick = 0L) {
    .Call(`_yaumap_run`, status, nthreads, tick)
}

