# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_from_matrix <- function(data, n_neighbors, nn_method, ndim) {
    .Call('_yaumap_initialize_from_matrix', PACKAGE = 'yaumap', data, n_neighbors, nn_method, ndim)
}

initialize_from_neighbors <- function(indices, distances, ndim) {
    .Call('_yaumap_initialize_from_neighbors', PACKAGE = 'yaumap', indices, distances, ndim)
}

run <- function(status, ndim, embedding) {
    .Call('_yaumap_run', PACKAGE = 'yaumap', status, ndim, embedding)
}

